format = "$all"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold yellow) "

[gcloud]
disabled = true

[helm]
disabled = true

[kubernetes]
symbol = '⛵ '
disabled = false
style = '70'

[directory]
truncation_length = 4
truncation_symbol = "…/"
home_symbol = '~'
style = '117'

[git_branch]
format = 'on [$symbol$branch]($style) '

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = 'purple'

[package]
disabled = true 
